# Generated by Django 4.2.4 on 2023-08-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='capacity',
        ),
        migrations.AddField(
            model_name='table',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='table',
            name='seats',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (6, '6')], default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_count',
            field=models.IntegerField(choices=[(2, '2'), (4, '4'), (5, '5'), (6, '6')], default=2),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guest_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
