# Generated by Django 4.2.4 on 2023-09-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_table_num_of_reservations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='canceled',
        ),
    ]
